# Generated by Django 3.0.6 on 2020-05-19 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_number', models.CharField(max_length=20, unique=True, verbose_name='Code Number')),
                ('full_name', models.CharField(max_length=300, verbose_name='Full Number')),
                ('shipping_address', models.CharField(max_length=200, verbose_name='Shipping Address')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('pub_date', models.DateField(default=datetime.datetime(2020, 5, 19, 12, 38, 45, 198017, tzinfo=utc))),
            ],
        ),
    ]
